### ISSUE TITLE
Store information about the state of database

### ISSUE THREAD

**Issue by qdequele** [meilisearch/MeiliDB#140]
Keep somewhere the number of documents stored and the total size for each index.

**Comment by hyc** [comment]
You should already have most of that for free, using mdb_stat.

**Comment by Kerollmops** [comment]
@hyc Do think that a simple calculus using the [`MDB_stat`](http://www.lmdb.tech/doc/group__mdb.html#structMDB__stat) `ms_psize`, `ms_leaf_pages` and `ms_branch_pages` fields would be correct to compute a database memory size?

```
(ms_leaf_pages + ms_branch_pages) * ms_psize
```

**Comment by hyc** [comment]
What do you mean by memory size? It would tell you a max; actual memory in use may be much less if the pages haven't been referenced recently.

**Comment by qdequele** [comment]
Could be close since 
https://github.com/meilisearch/MeiliDB/blob/e8251ad45b6de9b3cbb2d4b04c7b71f80f7754f0/meilidb-http/src/routes/stats.rs#L17-L61
