### ISSUE TITLE
Make the database schema less by default

### ISSUE THREAD

**Issue by qdequele** [meilisearch/MeiliDB#142]
If the schema configuration is not changed by the user. Make all fields indexed and stored. In all cases, keep all fields stored. That will allow the user to change, in the future, its schema without re-indexing all documents. This action will iterate over all index and recompute all the FST. 

We can also advance this idea with the possibility to store only 1 k-v for 1 document. Currently we are storing 1 k-v for each field on a document. We can keep this stored information until the user has not changed its retrievable fields.

> One field to rule them all, One field to find them, One field to bring them all and in the data bind them.

**Comment by Kerollmops** [comment]
We support index creation without schema, the schema will automatically be inferred by using the first document.

https://github.com/meilisearch/MeiliDB/blob/62fe6a82637b9b9cbb4f81cf912a96c5b45dd612/meilidb-http/src/routes/document.rs#L132-L152

https://github.com/meilisearch/MeiliDB/blob/62fe6a82637b9b9cbb4f81cf912a96c5b45dd612/meilidb-http/src/routes/document.rs#L171-L180
