### ISSUE TITLE
Returned body on index creation should contain the created elements

### ISSUE THREAD

**Issue by bidoubiwa** [meilisearch/MeiliDB#288]
route `POST /indexes/:index` should not send back a `204 no content`.

Even when no schema is given in the requested body

It should send back a `201 Created` with the created element.

```bash
HTTP/1.1 204 No Content
access-control-allow-origin: *
date: Wed, 13 Nov 2019 13:35:09 GMT
```
should be `201 created`
```json 
{
"index" : "myindex",
"schema" : null,
"updateId" : null
}
```

and when a schema is given 
```json 
{
"index" : "myindex",
"schema" : { "id": ["identifier"] },
"updateId" : 1
}
```

**Comment by Kerollmops** [comment]
Yeah, why not, could you please submit a pull request? Thank you
