### ISSUE TITLE
Should I always use Content-Type header?

### ISSUE THREAD

**Issue by tpayet** [meilisearch/MeiliDB#328]
As we are currently writing the documentation, we are wondering wether the header 'Content-type: application/json' is always required when making http call to meilidb-http server ?

**Comment by Kerollmops** [comment]
It is currently not mandatory, but I think I would prefer to specify it anyway.

**Comment by tpayet** [comment]
Is that okay if we are not putting it in each curl example but as a recommended headers at the beginning of the documentation? 
We will update this if it becomes a mandatory header

**Comment by Kerollmops** [comment]
Yes, no worries, it makes the examples easier to read 👍
